/** Stable machine-readable error codes used across API and agents. */
export const ERROR_CODES = {
  // Generic
  INTERNAL: 'INTERNAL',
  VALIDATION: 'VALIDATION',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  BAD_REQUEST: 'BAD_REQUEST',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',

  // Org / users
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_DISABLED: 'USER_DISABLED',
  INVITATION_INVALID: 'INVITATION_INVALID',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  SEAT_LIMIT_REACHED: 'SEAT_LIMIT_REACHED',

  // Devices / sessions
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_OFFLINE: 'DEVICE_OFFLINE',
  DEVICE_DISABLED: 'DEVICE_DISABLED',
  DEVICE_LIMIT_REACHED: 'DEVICE_LIMIT_REACHED',
  ENROLLMENT_INVALID: 'ENROLLMENT_INVALID',
  GUEST_LINK_INVALID: 'GUEST_LINK_INVALID',
  GUEST_LINK_EXPIRED: 'GUEST_LINK_EXPIRED',
  GUEST_LINK_EXHAUSTED: 'GUEST_LINK_EXHAUSTED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_NOT_ACTIVE: 'SESSION_NOT_ACTIVE',
  SESSION_LIMIT_REACHED: 'SESSION_LIMIT_REACHED',
  CONNECTION_FAILED: 'CONNECTION_FAILED',
  SIGNALING_ERROR: 'SIGNALING_ERROR',

  // Agent
  AGENT_COMMAND_TIMEOUT: 'AGENT_COMMAND_TIMEOUT',
  AGENT_COMMAND_FAILED: 'AGENT_COMMAND_FAILED',
  HEARTBEAT_STALE: 'HEARTBEAT_STALE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  details?: unknown;
  requestId?: string;
}

export function createApiError(
  code: ErrorCode,
  message: string,
  details?: unknown,
  requestId?: string,
): ApiErrorBody {
  return {
    code,
    message,
    ...(details !== undefined ? { details } : {}),
    ...(requestId !== undefined ? { requestId } : {}),
  };
}
